name: "Incremental - Synopsys Intelligent Security Scan"

on:
  pull_request:
    branches: 
      - '**'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2

    # If this run was triggered by a pull request event, then checkout
    # the head of the pull request instead of the merge commit.
    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}
    
    #- name: Binary Analysis with Black Duck
    #  run: bash <(curl -s https://detect.synopsys.com/detect.sh) \
    #      --blackduck.url="${{ secrets.BLACKDUCK_URL}}" \
    #      --blackduck.api.token="${{ secrets.BLACKDUCK_TOKEN}}" \
    #      --detect.tools="SIGNATURE_SCAN,DETECTOR" \
    #      --detect.binary.scan.file.path=./insecure-bank.war

    - name: Synopsys Intelligent Security Scan
      id: prescription
      uses: synopsys-sig/intelligent-security-scan@26a9e0c
      with:
        ioServerUrl: ${{secrets.IO_SERVER_URL1}}
        ioServerToken: ${{secrets.IO_SERVER_TOKEN1}}
        workflowServerUrl: ${{secrets.WORKFLOW_SERVER_URL1}}
        workflowServerToken: ${{secrets.WORKFLOW_SERVER_TOKEN1}}
        additionalWorkflowArgs: "--persona=developer --release.type=major --polaris.url=${{secrets.POLARIS_SERVER_URL}} --polaris.token=${{secrets.POLARIS_ACCESS_TOKEN}} --sensitive.package.pattern=com.synopsys.app --jira.project.name=aaaa --jira.assignee=aaaa --jira.api.url=aaaa --jira.issues.query=aaaa --jira.username=aaaa --jira.auth.token=aaaa"
        stage: "IO"
    
    - name: Print Prescription
      run: |      
          echo ${{steps.prescription.outputs.sastScan}}
          echo ${{steps.prescription.outputs.scaScan}}
    
    # Please note that the ID in previous step was set to prescription
    # in order for this logic to work also make sure that POLARIS_ACCESS_TOKEN
    # is defined in settings
    - name: Incremental Static Analysis with Polaris
      if: ${{steps.prescription.outputs.sastScan == 'true1' }}
      run: |      
          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
          FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
          echo $FILES | tr " " "\n" > polaris-files-to-scan.txt
          echo "Files Changed -->"
          cat polaris-files-to-scan.txt
          export POLARIS_SERVER_URL=${{ secrets.POLARIS_SERVER_URL}}
          export POLARIS_ACCESS_TOKEN=${{ secrets.POLARIS_ACCESS_TOKEN}}
          export POLARIS_FF_ENABLE_COVERITY_INCREMENTAL=true
          wget -q ${{ secrets.POLARIS_SERVER_URL}}/api/tools/polaris_cli-linux64.zip
          unzip -j polaris_cli-linux64.zip -d /tmp
          /tmp/polaris analyze -w --coverity-ignore-capture-failure --incremental polaris-files-to-scan.txt | tee polaris-output.txt
          
    # Please note that the ID in previous step was set to prescription
    # in order for this logic to work
    - name: Software Composition Analysis with Black Duck
      if: ${{steps.prescription.outputs.scaScan == 'true1' }}
      uses: blackducksoftware/github-action@v2
      with:
         args: '--blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_TOKEN}}" --detect.tools="DETECTOR"'
    
    - name: Binary Analysis with Black Duck
      if: ${{steps.prescription.outputs.scaScan == 'true1' }}
      run: bash <(curl -s https://detect.synopsys.com/detect.sh) \
          --blackduck.url="${{ secrets.BLACKDUCK_URL}}" \
          --blackduck.api.token="${{ secrets.BLACKDUCK_TOKEN}}" \
          --detect.tools="SIGNATURE_SCAN,DETECTOR" \
          --detect.binary.scan.file.path=./insecure-bank.war
  
    - name: Synopsys Intelligent Security Scan
      if: ${{ steps.prescription.outputs.sastScan == 'true' || steps.prescription.outputs.scaScan == 'true' }}
      uses: synopsys-sig/intelligent-security-scan@26a9e0c
      with:
        ioServerUrl: ${{secrets.IO_SERVER_URL1}}
        ioServerToken: ${{secrets.IO_SERVER_TOKEN1}}
        workflowServerUrl: ${{secrets.WORKFLOW_SERVER_URL1}}
        workflowServerToken: ${{secrets.WORKFLOW_SERVER_TOKEN1}}
        additionalWorkflowArgs: "--slack.channel.id=C015LGE7RRQ --slack.token=${{secrets.SLACK_TOKEN}} --IS_SAST_ENABLED=${{steps.prescription.outputs.sastScan}} --IS_SCA_ENABLED=${{steps.prescription.outputs.scaScan}} --polaris.project.name=sig-devsecops/github-io-sample --polaris.url=${{secrets.POLARIS_SERVER_URL}} --polaris.token=${{secrets.POLARIS_ACCESS_TOKEN}} --blackduck.project.name=github-io-sample:1.0.0 --blackduck.url=${{secrets.BLACKDUCK_URL}} --blackduck.api.token=${{secrets.BLACKDUCK_TOKEN}}"
        stage: "WORKFLOW"
    
    - name: Upload SARIF file
      if: ${{steps.prescription.outputs.sastScan == 'true' }}
      uses: github/codeql-action/upload-sarif@v1
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: workflowengine-results.sarif.json
